### ISSUE TITLE
Crash with Chains

### ISSUE THREAD

**Issue by WenXin20** [lilypuree/Decorative-Winter#2]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Decorative Blocks v1.7.0`
`Decorative Winter v0.1`

The mod crashes on launch due to being unable to find a `decorative_blocks:chain`
[Crash Report](https://gist.github.com/WenXin20/e16a267e6a9a36cf511ae4c13f221d61)

**Comment by lilypuree** [comment]
The new version on Curseforge will work.

**Comment by WenXin20** [comment]
Thanks!
