### ISSUE TITLE
Game wont start

### ISSUE THREAD

**Issue by CupOJo1** [lilypuree/Decorative-Winter#3]
[latest.log](https://github.com/lilypuree/Decorative-Winter/files/5740265/latest.log)

**Comment by lilypuree** [comment]
does it crash without optifine?

**Comment by CupOJo1** [comment]
yeah it does

**Comment by lilypuree** [comment]
I think this is a duplicate issue with issue #2, so I'll close it for now

**Comment by CupOJo1** [comment]
alrighty
