### ISSUE TITLE
0.1.1 - Crash - Rendering overlay

### ISSUE THREAD

**Issue by MisterShawn** [lilypuree/Decorative-Winter#4]
Crash report: https://gist.github.com/sdaddy/a0a21c28d94204cb35ae3f629d51af63

Let me know if you need any more information. Thanks!

**Comment by lilypuree** [comment]
Hopefully fixed by the update
[https://www.curseforge.com/minecraft/mc-mods/decorative-winter/files/3151003](https://www.curseforge.com/minecraft/mc-mods/decorative-winter/files/3151003)
