### ISSUE TITLE
Crashing on game launch [1.18.1]

### ISSUE THREAD

**Issue by brisingraerowing** [lilypuree/Decorative-Winter#8]
[Crash Log](https://gist.github.com/BrisingrAerowing/db5064a91e63520b1b870070da940e1a)

**Comment by Gbergz** [comment]
Can confirm : https://gist.github.com/Gbergz/a7ab22815e8d061716f6263fdd9ca022
Seems to be the new decorative blocks update that broke it. Rolling back to Decorative Blocks version 2.0.2 solves it.

**Versions:**
MC: **1.18.1** (obviously.)
Forge: **39.0.45**
Decorative Blocks: **2.0.4** | https://www.curseforge.com/minecraft/mc-mods/decorative-blocks/files/3613621
Decorative Winter: **2.0.0** | https://www.curseforge.com/minecraft/mc-mods/decorative-winter/files/3593505

**-** Gbergz

**Comment by xR4YM0ND** [comment]
Crashes here too

Modpack used: https://www.curseforge.com/minecraft/modpacks/the-progressor

Maybe with Inspecio or Decorative Blocks update?

Crash Report Client: https://gist.github.com/SpigotDE/4302540b3cec49ec62941a4aed66563b
Crash Report Server: https://gist.github.com/SpigotDE/54da33824a7991d95d735e1dd92acd24
Latest.Log: https://gist.github.com/SpigotDE/78269217f8fb0a442579a8af1069f541

**Comment by brisingraerowing** [comment]
I looked at the code, and the new Decorative Blocks update rearranged some of the classes, so DW is looking in the wrong place for them. Simple fix, as it looks like there weren't any changes to those classes other than moving them.

**Comment by lilypuree** [comment]
Fixed
